USE `uam`;

-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)
INSERT INTO USERS (id, username, password, first_name, last_name, email, phone_number, enabled, deleted, last_password_reset_date, created_on) VALUES (1, 'user', '$2a$04$sXODyYf3/tYJfwJQbbQc4OFU6V3Dc9yeYfuEEZKLKMNucfINBF29y', 'rachit', 'bhasin', 'user@example.com', '+1234567890', b'1', b'0', NOW(), NOW());
INSERT INTO USERS (id, username, password, first_name, last_name, email, phone_number, enabled, deleted, last_password_reset_date, created_on) VALUES (2, 'admin', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'admin', 'user', 'admin@example.com', '+0987654321', b'1', b'0', NOW(), NOW());

INSERT INTO AUTHORITY (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (id, name) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (user_id, authority_id) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (user_id, authority_id) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (user_id, authority_id) VALUES (2, 2);

INSERT INTO `book` (`id`, `created_on`, `last_modified_on`, `author`, `title`, `created_by`, `last_modified_by`) VALUES (1, NOW(), NULL, 'Rachit', 'test', 1, NULL);

